INSERT INTO chart_account (code, name, type, normal_balance, is_bank, is_system, description) VALUES
('1000', 'Cash on Hand', 'ASSET', 'DEBIT', false, true, 'key:cash_on_hand'),
('1010', 'Petty Cash', 'ASSET', 'DEBIT', false, false, null),
('1100', 'Bank — Current Account', 'ASSET', 'DEBIT', true, false, null),
('1110', 'M-Pesa Paybill / Till', 'ASSET', 'DEBIT', true, false, null),
('1200', 'Accounts Receivable (Debtors)', 'ASSET', 'DEBIT', false, true, 'key:accounts_receivable'),
('1300', 'Inventory — Finished Goods', 'ASSET', 'DEBIT', false, true, 'key:inventory'),
('1310', 'Inventory — Raw Materials', 'ASSET', 'DEBIT', false, true, 'key:raw_materials_inventory'),
('1400', 'VAT Input (Receivable)', 'ASSET', 'DEBIT', false, true, 'key:vat_input'),
('1500', 'Property, Plant & Equipment', 'ASSET', 'DEBIT', false, false, null),
('1510', 'Accumulated Depreciation', 'ASSET', 'CREDIT', false, false, null),
('2000', 'Accounts Payable (Creditors)', 'LIABILITY', 'CREDIT', false, true, 'key:accounts_payable'),
('2100', 'VAT Output (Payable)', 'LIABILITY', 'CREDIT', false, true, 'key:vat_output'),
('2110', 'PAYE Payable', 'LIABILITY', 'CREDIT', false, false, null),
('2120', 'NHIF Payable', 'LIABILITY', 'CREDIT', false, false, null),
('2130', 'NSSF Payable', 'LIABILITY', 'CREDIT', false, false, null),
('2200', 'Accrued Expenses', 'LIABILITY', 'CREDIT', false, false, null),
('2300', 'Loans Payable', 'LIABILITY', 'CREDIT', false, false, null),
('3000', "Owner's Capital", 'EQUITY', 'CREDIT', false, false, null),
('3100', 'Drawings', 'EQUITY', 'DEBIT', false, false, null),
('3200', 'Retained Earnings', 'EQUITY', 'CREDIT', false, true, 'key:retained_earnings'),
('4000', 'Sales Revenue', 'INCOME', 'CREDIT', false, true, 'key:sales_revenue'),
('4100', 'Other Income', 'INCOME', 'CREDIT', false, false, null),
('4200', 'Interest Income', 'INCOME', 'CREDIT', false, false, null),
('5000', 'Cost of Sales', 'EXPENSE', 'DEBIT', false, true, 'key:cost_of_sales'),
('5100', 'Salaries & Wages', 'EXPENSE', 'DEBIT', false, false, null),
('5200', 'Rent', 'EXPENSE', 'DEBIT', false, false, null),
('5210', 'Electricity & Water', 'EXPENSE', 'DEBIT', false, false, null),
('5220', 'Fuel & Transport', 'EXPENSE', 'DEBIT', false, false, null),
('5300', 'Repairs & Maintenance', 'EXPENSE', 'DEBIT', false, false, null),
('5400', 'Bank Charges', 'EXPENSE', 'DEBIT', false, false, null),
('5500', 'Telephone & Internet', 'EXPENSE', 'DEBIT', false, false, null),
('5600', 'Office & Administrative', 'EXPENSE', 'DEBIT', false, false, null),
('5700', 'Depreciation Expense', 'EXPENSE', 'DEBIT', false, false, null),
('5800', 'Professional Fees', 'EXPENSE', 'DEBIT', false, false, null)
ON CONFLICT (code) DO NOTHING;
